### PR TITLE
Newsweek website clone for milestone 3

### PR DESCRIPTION
**Pull request by uzairali19**
This website is a clone of the original [website](https://web.archive.org/web/20210120125445/https://www.newsweek.com/).

This is Milestone 3 of the project Using Bootstrap. In this part, we've added the last sections at the bottom of the website with corresponding responsiveness and style.

# The framework used here:
- Bootstrap

### CODE REVIEW

**Review by Dipeshtwis — CHANGES_REQUESTED** [review]
# Status:  ♻️ Changes Required ♻️
 Hi Team, Good work

**You've really hit all the requirements in one shot. Well done.** Here're the major highlights of this PR:
 
- [x] The content order and disposition changes to the correct place on the desktop, tablet, and mobile.

**However, in order to approve, we have to work a little bit more. Please check my comments below and fix them as appropriate.**

## For Approval

- [x] PR title and description should be descriptive. It must tell which section you have added or which feature you have worked on. 
- [x] The readme file is missing important information about the project, like what the project is all about, how to get a copy of the project, etc. 
- [x] The image is not showing in the **newsletter** section. Also, the header is not looking the same (you used black color but has a red with white background). See the image below.

Screenshot (1336)


- [ ] In the subscribe section, the text is over the image in mobile view but yours not. Kindly fix that and see the image below to get my point. Also, check the header color.

Screenshot (1337)_LI



## [Optional]

- [ ] I will recommend you to commit more often. This is the way to tell in which step what you've done (to others as well as yourself). 
Remember, This is optional and nothing to do with the project approval.

## Reminder

**"As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) now, you have only 2 code review left for this project."**


## Please make the required changes and submit another review request when you are done.

(Feel free to contact me on slack by the handle of  **deep** if you have any additional questions).
Happy Coding
[Dipesh Kumar](https://deeptwist.tk) | [Twitter](https://twitter.com/97deepeshkumar)

**Comment by uzairali19** [comment]
> # Status: ♻️ Changes Required ♻️
> Hi Team, Good work
> 
> **You've really hit all the requirements in one shot. Well done.** Here're the major highlights of this PR:
> 
> * [x]  The content order and disposition changes to the correct place on the desktop, tablet, and mobile.
> 
> **However, in order to approve, we have to work a little bit more. Please check my comments below and fix them as appropriate.**
> 
> ## For Approval
> * [ ]  PR title and description should be descriptive. It must tell which section you have added or which feature you have worked on.
> * [ ]  The readme file is missing important information about the project, like what the project is all about, how to get a copy of the project, etc.
> * [x]  The image is not showing in the **newsletter** section. Also, the header is not looking the same (you used black color but has a red with white background). See the image below.
> 
> Screenshot (1336)
> 
> * [ ]  In the subscribe section, the text is over the image in mobile view but yours not. Kindly fix that and see the image below to get my point. Also, check the header color.
> 
> Screenshot (1337)_LI
> 
> ## [Optional]
> * [ ]  I will recommend you to commit more often. This is the way to tell in which step what you've done (to others as well as yourself).
>   Remember, This is optional and nothing to do with the project approval.
> 
> ## Reminder
> **"As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) now, you have only 2 code review left for this project."**
> 
> ## Please make the required changes and submit another review request when you are done.
> (Feel free to contact me on slack by the handle of **deep** if you have any additional questions).
> Happy Coding
> [Dipesh Kumar](https://deeptwist.tk) | [Twitter](https://twitter.com/97deepeshkumar)

Hello,

Thank you for such a detailed review of my project. I do have the concern to share with you.

> * [ ]  In the subscribe section, the text is over the image in mobile view but yours not. Kindly fix that and see the image below to get my point. Also, check the header color.
> 
> Screenshot (1337)_LI
> 

This section that you mentioned has actually a bug in it. As you can see, the text on the image is not readable. So if this show on your screen, this is the wrong way to style your page. As the image has text on top which is not readable to the user. Kindly check thoroughly next time you review because this has really caused an issue for me and my partner to get this project done. The right way to display this section is for the text to go below that so that the user can read the title of the image and know what it is about.

If in any case i am not clear about my point please let me know. Otherwise, I would appreciate it if you can look into it. Thanks.

**Review by george-shammar — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUIRED** :recycle: :recycle: 

Great job and thank you for implementing most of the changes required from the previous review.

However, based on the feedback from your last review, below is an an outstanding change yet to be implemented.

- [ ] The subscribe/Newsletter section is different from the original. Please refer to the attached images by the previous reviewer. In the mobile view, the tittle of the subscribe section is displayed over the image in an absolute position while yours is displayed below. The color of the "Subscribe" text too differs. Yours is black while the original is red as pointed out earlier. 

As part of the project requirement, you were asked to be more precise and to make sure that your page looks exactly the same as the source page. Please implement this and submit another CRR when you're ready.

:red_circle:  **As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have only 1 code review left for this project. If you think that the code review was not fair, you can request a second-opinion using this[ form](https://airtable.com/shrQAqnBwek5a0O0s).**

**Review by george-shammar — APPROVED** [review]
### **STATUS: APPROVED** :heavy_check_mark: :heavy_check_mark: 

**Congratulations and thank you for implementing the required changes.** :+1: :ok_hand: 

**You've made a significant progress and your effort is commendable.**

**You can now go ahead and merge this branch**.

**I wish you goodluck with your future projects.**

**Cheers!** :wine_glass:

**Pull request merged**
